#compdef pnpm pn
#
# pnpm's zsh completion, generated by `pnpm completion zsh` (pnpm 11.21.0) and
# committed here rather than eval'd at startup. The setup pnpm's docs suggest,
# `eval "$(pnpm completion zsh)"` in ~/.zshrc, spawns a ~200ms Node process in
# every new shell just to print this same static text.
#
# zshrc.symlink sources every */completion.zsh *after* compinit, so the compdef
# branch below is the one that runs and the completion works in the shell that
# sources it -- no waiting on the daily background .zcompdump rebuild, which is
# what an $fpath + autoload setup would need. Line 1 is kept first regardless,
# so the file stays valid if it ever does move into $fpath.
#
# To regenerate: `pnpm completion zsh`, then put this header back on top.
#
# NB: each tab press on `pnpm` shells out to `pnpm completion-server`, a full
# Node startup (~200ms). It's per-command, so nothing else is affected.
###-begin-pnpm-completion-###
if type compdef &>/dev/null; then
  _pnpm_completion () {
    local reply
    local si=$IFS

    IFS=$'\n' reply=($(COMP_CWORD="$((CURRENT-1))" COMP_LINE="$BUFFER" COMP_POINT="$CURSOR" SHELL=zsh pnpm completion-server -- "${words[@]}"))
    IFS=$si

    if [ "$reply" = "__tabtab_complete_files__" ]; then
      _files
    else
      _describe 'values' reply
    fi
  }
  # When called by the Zsh completion system, this will end with
  # "loadautofunc" when initially autoloaded and "shfunc" later on, otherwise,
  # the script was "eval"-ed so use "compdef" to register it with the
  # completion system
  if [[ $zsh_eval_context == *func ]]; then
    _pnpm_completion "$@"
  else
    compdef _pnpm_completion pnpm pn
  fi
fi
###-end-pnpm-completion-###

